### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by lei-jpg** [0voice/Introduction-to-Golang#3]

**Comment by wenchao1024** [comment]
Where can't I open it?

**Comment by lei-jpg** [comment]
> Where can't I open it?
PPT，like this：
![image](https://user-images.githubusercontent.com/84887546/129670568-bb69c09e-2261-42de-8ecd-7ab75ca582f6.png)

**Comment by wenchao1024** [comment]
please download！
![image](https://user-images.githubusercontent.com/87457873/129704852-5debaf61-381a-47af-b74c-5caa1413686e.png)
